name = "spinogambinocasino-bonus-net"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinocasino-bonus.net"
HMAC_KEY = "e7183efdf92797f9e70dbabca94fe46f78708f6dd8a8b7edb303075b2454ab08"
COOKIE_NAME = "ikw"
PLAY_PATH = "go"
BUTTON_ID = "p9dd7faeb9db5aad17f5153592854b894"
GATE_SALT = "2c19d1586db9e716"
